### ISSUE TITLE
Need help #HacktoberFest  #Maintainer 

### ISSUE THREAD

**Issue by Deepu2002d** [sd2001/HacktoberFest2020#185]
Please help. Is there any maintainer in here who can check my contribution and than accept it? 
I made the PR yesterday and it's showing 13 days to become mature but only 7-8 days are left for October to end so, I need help from someone to mark my PR accepted after checking it. 
I am new and don't know where to contact a maintainer so, raising an issue.

**Comment by sd2001** [comment]
Not a problem. According to new guidelines, the review duration has been increased to 2 weeks. But any contributions till 31st October counts. Review period may extend till the first week of November, but it will count. No worries.Happy hacking
